# Preface {#sec-preface .unnumbered}

**Welcome to Yet Another R Dataviz Book!**

This book aims to provide a simple, easy-to-follow guide for making effective data visualizations in {{< fa brands r-project >}}.

Throughout the book, we keep the text to a minimum and focus on communicating key concepts as succinctly as possible. The general approach is to explain an idea in one or two sentences max, then provide an example with code so that you can see how to implement it.

The book leverages the [{ggplot2}](https://ggplot2.tidyverse.org/) package for making charts and [Quarto](https://quarto.org/) for making reproducible reports, and the book includes two introductory chapters on using these tools.

The book also includes a section on [Exploring Data](part2-exploring.qmd), including chapters on data cleaning, data transformation, and summarizing data using the [Tidyverse](https://www.tidyverse.org/).

Finally, the last section of the book is on [Data Visualization](part3-data-viz.qmd). Each chapter in this section includes examples of effective strategies for visualizing specific types of data and relationships.

This book is still very much in development, so if something seems off please feel free to [post an issue](https://github.com/jhelvy/yardbook/issues) on the GitHub repo and we'll address it ASAP.
